-- tweakunits = {
--     armassistdrone = {
--         buildoptions = {
--             [31] = "armclaw"
--         }
--     },
--     corassistdrone = {
--         buildoptions = {
--             [32] = "cormaw"
--         }
--     },
--     legassistdrone = {
--         buildoptions = {
--             [31] = "legdtl",
--             [32] = "legdtf"
--         }
--     },
--     armassistdrone_land = {
--         buildoptions = {
--             [31] = "armclaw"
--         }
--     },
--     corassistdrone_land = {
--         buildoptions = {
--             [32] = "cormaw"
--         }
--     },
--     legassistdrone_land = {
--         buildoptions = {
--             [31] = "legdtl",
--             [32] = "legdtf"
--         }
--     },
--     armshltx = {
--         buildoptions = {
--             [55] = "armassistdrone_land",
--             [56] = "corassistdrone_land",
--             [57] = "legassistdrone_land"
--         }
--     },
--     corgant = {
--         buildoptions = {
--             [55] = "armassistdrone_land",
--             [56] = "corassistdrone_land",
--             [57] = "legassistdrone_land"
--         }
--     },
--     leggant = {
--         buildoptions = {
--             [55] = "armassistdrone_land",
--             [56] = "corassistdrone_land",
--             [57] = "legassistdrone_land",
--             [58] = "legassistdrone_land"
--         }
--     },
--     armapt3 = {
--         buildoptions = {
--             [55] = "armassistdrone",
--             [56] = "corassistdrone",
--             [57] = "legassistdrone",
--             [58] = "armsat"
--         }
--     },
--     corapt3 = {
--         buildoptions = {
--             [55] = "armassistdrone",
--             [56] = "corassistdrone",
--             [57] = "legassistdrone",
--             [58] = "corsat"
--         }
--     },
--     legaca = {
--         buildoptions = {
--             [55] = "cormwall"
--         }
--     },
--     legack = {
--         buildoptions = {
--             [55] = "cormwall"
--         }
--     },
--     legacv = {
--         buildoptions = {
--             [55] = "cormwall"
--         }
--     },
-- }

-- -- base64url encoded
