return {}
-- tweakunits = {
--     cortron = {
--         energycost = 42000,
--         metalcost = 3600,
--         buildtime = 120000,
--         health = 12000,
--         weapondefs = {
--             cortron_weapon = {
--                 energypershot = 51000,
--                 metalpershot = 600,
--                 range = 3650,
--                 damage = {
--                     default = 9000 }
--             }
--         }
--     },
--     corfort = {
--         repairable = true },
--     armfort = {
--         repairable = true },
--     corscavfort = {
--         repairable = true },
--     armgate = {
--         explodeas = "empblast", selfdestructas = "empblast" },
--     corgate = {
--         explodeas = "empblast", selfdestructas = "empblast" },
--     corsat = {
--         sightdistance = 3100, radardistance = 4080, cruisealtitude = 3300, energyupkeep = 1250 },
--     armsat = {
--         sightdistance = 3100, radardistance = 4080, cruisealtitude = 3300, energyupkeep = 1250 },
--     legstarfall = {
--         weapondefs = {
--             starfire = {
--                 energypershot = 270000 }
--         }
--     },
--     armflak = {
--         airsightdistance = 1350,
--         energycost = 19000,
--         metalcost = 1500,
--         health = 4000,
--         weapondefs = {
--             armflak_gun = {
--                 range = 1100, reloadtime = 0.475, intensity = 0.38 }
--         }
--     },
--     armfflak = {
--         airsightdistance = 1350,
--         energycost = 25000,
--         metalcost = 1500,
--         health = 4000,
--         weapondefs = {
--             armflak_gun = {
--                 range = 1050, reloadtime = 0.475 }
--         }
--     },
--     corflak = {
--         airsightdistance = 1350,
--         energycost = 19000,
--         metalcost = 1500,
--         health = 4000,
--         weapondefs = {
--             armflak_gun = {
--                 areaofeffect = 300, range = 1350, reloadtime = 0.55, intensity = 0.38 }
--         }
--     },
--     corenaa = {
--         airsightdistance = 1350,
--         energycost = 25000,
--         metalcost = 1500,
--         health = 4000,
--         weapondefs = {
--             armflak_gun = {
--                 areaofeffect = 300, range = 1350, reloadtime = 0.55 }
--         }
--     },
--     legflak = {
--         airsightdistance = 1350,
--         energycost = 19000,
--         metalcost = 1500,
--         health = 4000,
--         weapondefs = {
--             legflak_gun = {
--                 areaofeffect = 100, burst = 3, range = 1050, reloadtime = 0.166, intensity = 0.38 }
--         }
--     },
--     armmercury = {
--         airsightdistance = 2200,
--         customparams = {
--             stockpilelimit = 30 },
--         weapondefs = {
--             arm_advsam = {
--                 areaofeffect = 500, energypershot = 2000, explosiongenerator = "custom:flak", flighttime = 1.5, metalpershot = 6, name = "Mid-range, rapid-fire g2a guided missile launcher", range = 2000, reloadtime = 0.8, smoketrail = false, startvelocity = 1500, stockpile = true, stockpiletime = 5, weaponacceleration = 1000, weaponvelocity = 4000 }
--         }
--     },
--     corscreamer = {
--         airsightdistance = 2800,
--         customparams = {
--             stockpilelimit = 20 },
--         weapondefs = {
--             cor_advsam = {
--                 areaofeffect = 800, energypershot = 2000, explosiongenerator = "custom:flak", flighttime = 1, metalpershot = 10, name = "Long-range g2a guided heavy flak missile launcher", range = 2600, reloadtime = 1.4, smoketrail = false, startvelocity = 4000, stockpile = true, stockpiletime = 7, weaponacceleration = 1000, weaponvelocity = 8000 }
--         }
--     },
--     armassistdrone = {
--         energycost = 2000,
--         metalcost = 100,
--         buildtime = 1200,
--         workertime = 50,
--         buildoptions = {
--             [
--             31] = "armclaw"
--         }
--     },
--     corassistdrone = {
--         energycost = 2000,
--         metalcost = 100,
--         buildtime = 1200,
--         workertime = 50,
--         buildoptions = {
--             [
--             32] = "cormaw"
--         }
--     },
--     legassistdrone = {
--         energycost = 2000,
--         metalcost = 100,
--         buildtime = 1200,
--         workertime = 50,
--         buildoptions = {
--             [
--             31] = "legdtl",
--             [32] = "legdtf"
--         }
--     },
--     armassistdrone_land = {
--         energycost = 1000,
--         metalcost = 100,
--         buildtime = 1000,
--         buildoptions = {
--             [
--             31] = "armclaw"
--         }
--     },
--     corassistdrone_land = {
--         energycost = 1000,
--         metalcost = 100,
--         buildtime = 1000,
--         buildoptions = {
--             [
--             32] = "cormaw"
--         }
--     },
--     legassistdrone_land = {
--         energycost = 1000,
--         metalcost = 100,
--         buildtime = 1000,
--         buildoptions = {
--             [
--             31] = "legdtl",
--             [32] = "legdtf"
--         }
--     },
--     raptor_hive = {
--         weapondefs = {
--             antiground = {
--                 reloadtime = 2, burst = 1, burstrate = 0.001 }
--         }
--     },
--     armshltx = {
--         buildoptions = {
--             [
--             55] = "armassistdrone_land",
--             [56] = "corassistdrone_land",
--             [57] = "legassistdrone_land"
--         }
--     },
--     corgant = {
--         buildoptions = {
--             [
--             55] = "armassistdrone_land",
--             [56] = "corassistdrone_land",
--             [57] = "legassistdrone_land"
--         }
--     },
--     leggant = {
--         buildoptions = {
--             [
--             55] = "armassistdrone_land",
--             [56] = "corassistdrone_land",
--             [57] = "legassistdrone_land",
--             [58] = "legassistdrone_land"
--         }
--     },
--     armapt3 = {
--         buildoptions = {
--             [
--             55] = "armassistdrone",
--             [56] = "corassistdrone",
--             [57] = "legassistdrone",
--             [58] = "armsat"
--         }
--     },
--     corapt3 = {
--         buildoptions = {
--             [
--             55] = "armassistdrone",
--             [56] = "corassistdrone",
--             [57] = "legassistdrone",
--             [58] = "corsat"
--         }
--     },
--     legaca = {
--         buildoptions = {
--             [
--             55] = "cormwall"
--         }
--     },
--     legack = {
--         buildoptions = {
--             [
--             55] = "cormwall"
--         }
--     },
--     legacv = {
--         buildoptions = {
--             [
--             55] = "cormwall"
--         }
--     },
--     armlwall = {
--         energycost = 21000,
--         metalcost = 1250,
--         weapondefs = {
--             lightning = {
--                 energypershot = 50, range = 425 }
--         }
--     },
--     armclaw = {
--         weapondefs = {
--             dclaw = {
--                 energypershot = 20 }
--         }
--     },
--     legdtl = {
--         weapondefs = {
--             dclaw = {
--                 energypershot = 20 }
--         }
--     },
--     armamd = {
--         metalcost = 1650,
--         energycost = 41000,
--         weapondefs = {
--             amd_rocket = {
--                 coverage = 2125, stockpiletime = 70 }
--         }
--     },
--     corfmd = {
--         metalcost = 1650,
--         energycost = 41000,
--         weapondefs = {
--             fmd_rocket = {
--                 coverage = 2125, stockpiletime = 70 }
--         }
--     },
--     armrespawn = {
--         blocking = false },
--     correspawn = {
--         blocking = false },
--     cormwall = {
--         energycost = 18000,
--         metalcost = 1250,
--         weapondefs = {
--             exp_heavyrocket = {
--                 areaofeffect = 70,
--                 collidefriendly = 0,
--                 collidefeature = 0,
--                 cameraShake = 0,
--                 energypershot = 50,
--                 avoidfeature = 0,
--                 avoidfriendly = 0,
--                 burst = 1,
--                 burstrate = 0,
--                 colormap = "0.75 0.73 0.67 0.024   0.37 0.4 0.30 0.021   0.22 0.21 0.14 0.018  0.024 0.014 0.009 0.03   0.0 0.0 0.0 0.008",
--                 craterareaofeffect = 0,
--                 explosiongenerator = "custom:burnblack",
--                 flamegfxtime = 1,
--                 flighttime = 1.05,
--                 name = "Raptor Boomer",
--                 reloadtime = 1.5,
--                 rgbcolor = "1 0.25 0.1",
--                 range = 700,
--                 size = 2,
--                 proximitypriority = {},
--                 impactonly = 1,
--                 trajectoryheight = 1,
--                 targetmoveerror = 0.2,
--                 tracks = true,
--                 weaponacceleration = 660,
--                 weaponvelocity = 950,
--                 damage = {
--                     default = 1050 }
--             }
--         }
--     },
--     cormaw = {
--         metalcost = 350,
--         energycost = 2500,
--         weapondefs = {
--             dmaw = {
--                 collidefriendly = 0,
--                 collidefeature = 0,
--                 areaofeffect = 80,
--                 edgeeffectiveness = 0.45,
--                 energypershot = 20,
--                 burst = 24,
--                 sizegrowth = 1,
--                 range = 450,
--                 intensity = 0.38,
--                 damage = {
--                     default = 28 }
--             }
--         }
--     },
--     legdtf = {
--         metalcost = 350,
--         energycost = 2750,
--         weapondefs = {
--             dmaw = {
--                 collidefriendly = 0,
--                 collidefeature = 0,
--                 areaofeffect = 80,
--                 edgeeffectiveness = 0.45,
--                 energypershot = 20,
--                 burst = 24,
--                 sizegrowth = 2,
--                 range = 450,
--                 intensity = 0.38,
--                 sprayangle = 500,
--                 damage = {
--                     default = 30 }
--             }
--         }
--     },
--     corhllllt = {
--         metalcost = 350,
--         energycost = 8000,
--         health = 2070,
--         weapondefs = {
--             hllt_1 = {
--                 energypershot = 10,
--                 damage = {
--                     default = 70 }
--             },
--             hllt_2 = {
--                 energypershot = 10,
--                 damage = {
--                     default = 70 }
--             },
--             hllt_3 = {
--                 energypershot = 10,
--                 damage = {
--                     default = 70 }
--             },
--             hllt_4 = {
--                 energypershot = 10,
--                 damage = {
--                     default = 70 }
--             }
--         }
--     },
--     armbrtha = {
--         explodeas = "fusionExplosion",
--         energycost = 500000,
--         metalcost = 18500,
--         buildtime = 170000,
--         turnrate = 16000,
--         health = 10450,
--         weapondefs = {
--             ata = {
--                 areaofeffect = 96,
--                 avoidFriendly = false,
--                 avoidFeature = false,
--                 collideFriendly = false,
--                 collideFeature = true,
--                 beamtime = 2.5,
--                 corethickness = 0.1,
--                 craterareaofeffect = 90,
--                 craterboost = 0,
--                 cratermult = 0,
--                 cameraShake = 0,
--                 edgeeffectiveness = 0.30,
--                 energypershot = 8500,
--                 explosiongenerator = "custom:laserhit-large-blue",
--                 firestarter = 90,
--                 impulseboost = 0,
--                 impulsefactor = 0,
--                 largebeamlaser = true,
--                 laserflaresize = 1,
--                 name = "Expermental Duction Beam",
--                 noselfdamage = true,
--                 range = 2300,
--                 reloadtime = 12,
--                 rgbcolor = "0.4 0.2 0.6",
--                 scrollspeed = 13,
--                 soundhitdry = "",
--                 soundhitwet = "sizzle",
--                 soundstart = "annigun1",
--                 soundtrigger = 1,
--                 targetmoveerror = 0.3,
--                 texture3 = "largebeam",
--                 thickness = 14,
--                 tilelength = 150,
--                 tolerance = 10000,
--                 turret = true,
--                 turnrate = 16000,
--                 weapontype = "LaserCannon",
--                 weaponvelocity = 3100,
--                 proximitypriority = 4,
--                 damage = {
--                     commanders = 480, default = 40000 }
--             }
--         },
--         weapons = {
--             [
--             1] = {
--                 badtargetcategory = "VTOL GROUNDSCOUT", def = "ATA", onlytargetcategory = "SURFACE" }
--         }
--     },
--     corint = {
--         explodeas = "fusionExplosion",
--         energycost = 505000,
--         metalcost = 19500,
--         buildtime = 170000,
--         health = 10450,
--         footprintx = 6,
--         footprintz = 6,
--         weapondefs = {
--             ata = {
--                 areaofeffect = 155,
--                 avoidFriendly = false,
--                 avoidFeature = false,
--                 collideFriendly = false,
--                 collideFeature = true,
--                 beamtime = 2.5,
--                 corethickness = 0.1,
--                 craterareaofeffect = 90,
--                 craterboost = 0,
--                 cratermult = 0,
--                 cameraShake = 0,
--                 edgeeffectiveness = 0.30,
--                 energypershot = 10000,
--                 explosiongenerator = "custom:laserhit-large-blue",
--                 firestarter = 90,
--                 impulseboost = 0,
--                 impulsefactor = 0,
--                 largebeamlaser = true,
--                 laserflaresize = 1,
--                 name = "Mini DeathStar",
--                 noselfdamage = true,
--                 range = 2500,
--                 reloadtime = 15,
--                 rgbcolor = "0 1 0",
--                 scrollspeed = 13,
--                 soundhitdry = "",
--                 soundhitwet = "sizzle",
--                 soundstart = "annigun1",
--                 soundtrigger = 1,
--                 targetmoveerror = 0.3,
--                 texture3 = "largebeam",
--                 thickness = 14,
--                 tilelength = 150,
--                 tolerance = 10000,
--                 turret = true,
--                 turnrate = 1600,
--                 weapontype = "LaserCannon",
--                 weaponvelocity = 3100,
--                 proximitypriority = 4,
--                 damage = {
--                     commanders = 480, default = 45000 }
--             }
--         },
--         weapons = {
--             [
--             1] = {
--                 badtargetcategory = "VTOL GROUNDSCOUT", def = "ATA", onlytargetcategory = "SURFACE" }
--         }
--     }
-- }

-- -- tweakdefs
-- local UnitDefs = UnitDefs or {}
-- local function a(b, c) for d, e in pairs(c) do if type(e) == "table" and type(b[d]) == "table" then a(b[d], e) else b[d] = e end end end; function deepCopy(c, f)
--     f = f or {}
--     local g = {}
--     f[c] = g; for d, e in pairs(c) do if type(e) == "table" then g[d] = f[e] or deepCopy(e, f) else g[d] = e end end; return g
-- end; function addWeapon(h, i, j)
--     UnitDefs[h] = UnitDefs[h] or {}
--     UnitDefs[h].weapons = UnitDefs[h].weapons or {}
--     UnitDefs[h].weapondefs = UnitDefs[h].weapondefs or {}
--     UnitDefs[h].customparams = UnitDefs[h].customparams or {}
--     local k = "repulsor"
--     table.insert(UnitDefs[h].weapons, { def = k, onlytargetcategory = j or "" })
--     UnitDefs[h].weapondefs[k] = i; if i.shield and i.shield.power > 0 then
--         i.range = i.shield.radius; UnitDefs[h].customparams = UnitDefs[h].customparams or {}
--         a(UnitDefs[h].customparams, { off_on_stun = "true", shield_color_mult = 0.8, shield_power = i.shield.power, shield_radius = i.shield.radius })
--     end
-- end; local l = { avoidfeature = false, craterareaofeffect = 0, craterboost = 0, cratermult = 0, edgeeffectiveness = 0.15, name = "PlasmaRepulsor", range = 50, soundhitwet = "sizzle", weapontype = "Shield", damage = { default = 100 }, shield = { alpha = 0.15, armortype = "shields", energyuse = 1, force = 2.5, intercepttype = 1, power = 500, powerregen = 3, powerregenenergy = 5, radius = 50, repulser = true, smart = true, startingpower = 100, visiblerepulse = true, badcolor = { 1, 0.2, 0.2, 0.2 }, goodcolor = { 0.2, 1, 0.2, 0.17 } } }
-- local m = { "armcom", "corcom", "legcom", "legcomlvl2", "legcomlvl3", "legcomlvl4", "legcomecon", "legcomoff", "legcomt2off" }
-- for n, h in ipairs(m) do
--     local o = deepCopy(l)
--     o.shield.alpha = 0.15; o.shield.power = 500; o.shield.radius = 100; o.shield.powerregen = 3; o.shield.powerregenenergy = 3; addWeapon(h, o)
-- end; for p, q in pairs(UnitDefs) do
--     if string.sub(p, 1, 24) == "raptor_air_fighter_basic" then
--         if q.weapondefs then
--             for r, s in pairs(q.weapondefs) do
--                 s.name = "Spike"
--                 s.accuracy = 200; s.collidefriendly = 0; s.collidefeature = 0; s.avoidfeature = 0; s.avoidfriendly = 0; s.areaofeffect = 64; s.edgeeffectiveness = 0.3; s.explosiongenerator = "custom:raptorspike-large-sparks-burn"
--                 s.cameraShake = {}
--                 s.dance = {}
--                 s.interceptedbyshieldtype = 0; s.model = "Raptors/spike.s3o"
--                 s.reloadtime = 1.1; s.soundstart = "talonattack"
--                 s.startvelocity = 200; s.submissile = 1; s.smoketrail = 0; s.smokePeriod = {}
--                 s.smoketime = {}
--                 s.smokesize = {}
--                 s.smokecolor = {}
--                 s.soundhit = {}
--                 s.texture1 = {}
--                 s.texture2 = {}
--                 s.tolerance = {}
--                 s.tracks = 0; s.turnrate = 60000; s.weaponacceleration = 100; s.weapontimer = 1; s.weaponvelocity = 1000; s.weapontype = {}
--                 s.wobble = {}
--             end
--         end
--     end
-- end; if UnitDefs then
--     UnitDefs.raptor_air_kamikaze_basic_t2_v1.selfdestructas = "raptor_empdeath_big"
--     UnitDefs.raptor_land_swarmer_emp_t2_v1.weapondefs.raptorparalyzersmall.damage.shields = 60; UnitDefs.raptor_land_swarmer_emp_t2_v1.weapondefs.raptorparalyzersmall.paralyzetime = 6; UnitDefs.raptor_land_assault_emp_t2_v1.weapondefs.raptorparalyzerbig.damage.shields = 140; UnitDefs.raptor_land_assault_emp_t2_v1.weapondefs.raptorparalyzerbig.paralyzetime = 10; UnitDefs.raptor_allterrain_arty_emp_t2_v1.weapondefs.goolauncher.paralyzetime = 6; UnitDefs.raptor_allterrain_arty_emp_t4_v1.weapondefs.goolauncher.paralyzetime = 10; UnitDefs.raptor_air_bomber_emp_t2_v1.cruisealtitude =
--         UnitDefs.raptor_air_bomber_emp_t2_v1.cruisealtitude + 400; UnitDefs.raptor_air_bomber_emp_t2_v1.weapondefs.weapon.damage.shields = 1000; UnitDefs.raptor_air_bomber_emp_t2_v1.weapondefs.weapon.damage.default = 2000; UnitDefs.raptor_air_bomber_emp_t2_v1.weapondefs.weapon.paralyzetime = 10; UnitDefs.raptor_allterrain_swarmer_emp_t2_v1.weapondefs.raptorparalyzersmall.paralyzetime = 6; UnitDefs.raptor_allterrain_swarmer_emp_t2_v1.weapondefs.raptorparalyzersmall.damage.shields = 60; UnitDefs.raptor_allterrain_assault_emp_t2_v1.weapondefs.raptorparalyzerbig.paralyzetime = 6; UnitDefs.raptor_allterrain_assault_emp_t2_v1.weapondefs.raptorparalyzerbig.damage.shields = 140; UnitDefs.raptor_matriarch_electric.weapondefs.goo.paralyzetime = 13; UnitDefs.raptor_matriarch_electric.weapondefs.melee.paralyzetime = 13; UnitDefs.raptor_matriarch_electric.weapondefs.spike_emp_blob.paralyzetime = 13; UnitDefs.armcom.featuredefs.dead.reclaimable = false; UnitDefs.armcom.featuredefs.dead.damage = 57600; UnitDefs.corcom.featuredefs.dead.reclaimable = false; UnitDefs.corcom.featuredefs.dead.damage = 57600; UnitDefs.legcom.featuredefs.dead.reclaimable = false; UnitDefs.legcom.featuredefs.dead.damage = 57600; UnitDefs.legcomlvl2.featuredefs.dead.reclaimable = false; UnitDefs.legcomlvl2.featuredefs.dead.damage = 57600; UnitDefs.legcomlvl3.featuredefs.dead.reclaimable = false; UnitDefs.legcomlvl3.featuredefs.dead.damage = 57600; UnitDefs.legcomlvl4.featuredefs.dead.reclaimable = false; UnitDefs.legcomlvl4.featuredefs.dead.damage = 57600; UnitDefs.legcomecon.featuredefs.dead.reclaimable = false; UnitDefs.legcomecon.featuredefs.dead.damage = 57600; UnitDefs.legcomt2def.featuredefs.dead.reclaimable = false; UnitDefs.legcomt2def.featuredefs.dead.damage = 57600; UnitDefs.legcomt2off.featuredefs.dead.reclaimable = false; UnitDefs.legcomt2off.featuredefs.dead.damage = 57600; UnitDefs.legcomoff.featuredefs.dead.reclaimable = false; UnitDefs.legcomoff.featuredefs.dead.damage = 57600
-- end; local t = { "raptor_antinuke", "raptor_turret_acid_t2_v1", "raptor_turret_acid_t3_v1", "raptor_turret_acid_t4_v1", "raptor_turret_antiair_t2_v1", "raptor_turret_antiair_t3_v1", "raptor_turret_antiair_t4_v1", "raptor_turret_antinuke_t2_v1", "raptor_turret_antinuke_t3_v1", "raptor_turret_antinuke_t4_v1", "raptor_turret_basic_t2_v1", "raptor_turret_basic_t3_v1", "raptor_turret_basic_t4_v1", "raptor_turret_burrow_t2_v1", "raptor_turret_emp_t2_v1", "raptor_turret_emp_t3_v1", "raptor_turret_emp_t4_v1", "raptor_worm_green" }
-- for p, u in pairs(UnitDefs) do
--     for r, v in ipairs(t) do
--         if p == v then
--             u.maxthisunit = 10; u.health = u.health * 2; if u.weapondefs then for r, s in pairs(u.weapondefs) do s.reloadtime = s.reloadtime / 2 end end; break
--         end
--     end
-- end
